/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendVerificationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authenticatedUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["allUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PostInput: {
            isbn: string;
            name: string;
            /** Format: int32 */
            pages: number;
            /** Format: int32 */
            year: number;
            description?: string;
        };
        PostOuput: {
            /** Format: int64 */
            id?: number;
            isbn?: string;
            name?: string;
            /** Format: int32 */
            pages?: number;
            /** Format: int32 */
            year?: number;
            description?: string;
        };
        VerifyUserDto: {
            email?: string;
            verificationCode?: string;
        };
        RegisterUserDto: {
            email?: string;
            password?: string;
            username?: string;
        };
        BookEntity: {
            /** Format: int64 */
            id?: number;
            isbn?: string;
            name?: string;
            /** Format: int32 */
            pages?: number;
            /** Format: int32 */
            year?: number;
            description?: string;
            image?: string;
            /** Format: int64 */
            idGenre?: number;
            /** Format: int64 */
            idUserBook?: number;
            /** Format: int64 */
            idWishlist?: number;
            /** Format: date-time */
            createAt?: string;
            genre?: components["schemas"]["GenreEntity"];
            userBooks?: components["schemas"]["UserBookEntity"][];
            likedByUsers?: components["schemas"]["LikedEntity"][];
            wishlistedByUsers?: components["schemas"]["WishlistEntity"][];
        };
        GenreEntity: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int64 */
            idBook?: number;
            books?: components["schemas"]["BookEntity"][];
        };
        GrantedAuthority: {
            authority?: string;
        };
        LikedEntity: {
            /** Format: int64 */
            id?: number;
            user?: unknown;
            book?: components["schemas"]["BookEntity"];
            /** Format: date-time */
            likedAt?: string;
        };
        User: {
            /** Format: int64 */
            id?: number;
            username?: string;
            email?: string;
            password?: string;
            refreshToken?: string;
            /** Format: int64 */
            idUserBooks?: number;
            enabled?: boolean;
            verificationCode?: string;
            /** Format: date-time */
            verificationCodeExpiresAt?: string;
            userBooks?: components["schemas"]["UserBookEntity"][];
            likedBooks?: components["schemas"]["LikedEntity"][];
            wishlist?: components["schemas"]["WishlistEntity"][];
            authorities?: components["schemas"]["GrantedAuthority"][];
            credentialsNonExpired?: boolean;
            accountNonExpired?: boolean;
            accountNonLocked?: boolean;
        };
        UserBookEntity: {
            /** Format: int64 */
            id?: number;
            user?: components["schemas"]["User"];
            book?: components["schemas"]["BookEntity"];
            /** Format: int32 */
            pagesRead?: number;
            /** Format: date-time */
            finishAt?: string;
            /** @enum {string} */
            status?: "TO_READ" | "READING" | "FINISHED";
        };
        WishlistEntity: {
            /** Format: int64 */
            id?: number;
            user?: unknown;
            book?: components["schemas"]["BookEntity"];
        };
        LoginUserDto: {
            email?: string;
            password?: string;
        };
        LoginResponse: {
            token?: string;
            /** Format: int64 */
            expiresIn?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createBook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostOuput"];
                };
            };
        };
    };
    verifyUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyUserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    resendVerificationCode: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    authenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginUserDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    authenticatedUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    allUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"][];
                };
            };
        };
    };
}
